import { parse } from "yaml";
import { z } from "zod";

const fieldNamePattern = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const stringPropertySchema = z
  .object({
    type: z.literal("string"),
  })
  .passthrough();

const openApiDocumentSchema = z.object({
  openapi: z.string(),
  components: z.object({
    schemas: z.object({
      User: z.object({
        type: z.literal("object"),
        required: z.array(z.string()),
        properties: z.record(z.string(), stringPropertySchema),
      }),
    }),
  }),
});

export function renderGeneratedClient(openApiSource: string): string {
  const document = openApiDocumentSchema.parse(parse(openApiSource));
  const userSchema = document.components.schemas.User;
  const requiredFields = new Set(userSchema.required);

  for (const requiredField of requiredFields) {
    if (!(requiredField in userSchema.properties)) {
      throw new Error(`Required field is missing from properties: ${requiredField}`);
    }
  }

  const fields = Object.keys(userSchema.properties).map((fieldName) => {
    if (!fieldNamePattern.test(fieldName)) {
      throw new Error(`Field name is not a valid TypeScript identifier: ${fieldName}`);
    }

    const optionalMarker = requiredFields.has(fieldName) ? "" : "?";
    return `  ${fieldName}${optionalMarker}: string;`;
  });

  return [
    "// Generated by scripts/generate-client.ts from api/openapi.yaml.",
    "",
    "export interface User {",
    ...fields,
    "}",
    "",
    "export function buildUserUrl(baseUrl: string, userId: string): string {",
    '  const normalizedBaseUrl = baseUrl.endsWith("/") ? baseUrl.slice(0, -1) : baseUrl;',
    "  return `${normalizedBaseUrl}/users/${encodeURIComponent(userId)}`;",
    "}",
    "",
  ].join("\n");
}
